[package]
name = "bgl-migrator-program"
version = "0.1.0"
edition = "2021"
readme = "./README.md"
license-file = "../../LICENSE"
publish = false

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
borsh = "^0.10"
shank = "0.4.2"
num-derive = "0.4.2"
num-traits = "^0.2"
solana-program = "1.18.16"
thiserror = "^1.0"
mpl-core = "0.7.1"
mpl-token-metadata = "4.1.2"
